import { WerewolfPersonality, PersonalityProfile } from './werewolfTypes';

export const PERSONALITY_PROFILES: Record<WerewolfPersonality, PersonalityProfile> = {
  cautious: {
    id: 'cautious',
    name: 'Thận Trọng',
    badge: '🛡️',
    description: 'Ít mạo hiểm, luôn ưu tiên bảo toàn tính mạng và tin cậy những người có bằng chứng rõ ràng.',
    riskTolerance: 0.2,
    aggression: 0.2,
    skepticism: 0.6,
    memoryRetention: 0.9,
  },
  aggressive: {
    id: 'aggressive',
    name: 'Quyết Đoán',
    badge: '⚡',
    description: 'Hành động nhanh, dứt khoát, ưu tiên loại bỏ các mục tiêu nguy hiểm hoặc có sức ảnh hưởng.',
    riskTolerance: 0.8,
    aggression: 0.9,
    skepticism: 0.7,
    memoryRetention: 0.6,
  },
  suspicious: {
    id: 'suspicious',
    name: 'Đa Nghi',
    badge: '👁️',
    description: 'Dễ nghi ngờ hành vi bất thường của người khác, điểm hoài nghi thay đổi liên tục.',
    riskTolerance: 0.4,
    aggression: 0.6,
    skepticism: 0.95,
    memoryRetention: 0.8,
  },
  logical: {
    id: 'logical',
    name: 'Lý Trí',
    badge: '🧠',
    description: 'Phân tích dựa trên chuỗi sự kiện lịch sử, loại trừ mâu thuẫn để đưa ra quyết định chuẩn xác.',
    riskTolerance: 0.5,
    aggression: 0.4,
    skepticism: 0.75,
    memoryRetention: 0.95,
  },
  loyal: {
    id: 'loyal',
    name: 'Trung Thành',
    badge: '🤝',
    description: 'Bảo vệ đồng minh, tin tưởng vào những người từng giúp đỡ mình hoặc đã được kiểm chứng.',
    riskTolerance: 0.6,
    aggression: 0.3,
    skepticism: 0.3,
    memoryRetention: 0.85,
  },
  chaotic: {
    id: 'chaotic',
    name: 'Khó Đoán',
    badge: '🎲',
    description: 'Hành động bất ngờ, linh hoạt, đôi khi đưa ra quyết định khó lường nhưng có tính đột biến.',
    riskTolerance: 0.9,
    aggression: 0.7,
    skepticism: 0.5,
    memoryRetention: 0.5,
  },
  observant: {
    id: 'observant',
    name: 'Tinh Tế',
    badge: '🔍',
    description: 'Ghi nhớ chi tiết từng diễn biến ban đêm, phát hiện những chi tiết mà người khác bỏ qua.',
    riskTolerance: 0.3,
    aggression: 0.3,
    skepticism: 0.8,
    memoryRetention: 1.0,
  },
};

export interface NPCBaseTemplate {
  id: string;
  name: string;
  avatar: string;
  age: number;
  job: string;
  bio: string;
  defaultPersonality: WerewolfPersonality;
  houseColor: string;
}

export const ALL_VILLAGE_NPCS: NPCBaseTemplate[] = [
  // 1. Trưởng lão & Người giữ chìa khóa
  {
    id: 'npc_01',
    name: 'Cụ An',
    avatar: '👴',
    age: 68,
    job: 'Trưởng Thôn',
    bio: 'Người uyên bác nắm giữ chìa khóa tháp chuông làng cổ.',
    defaultPersonality: 'cautious',
    houseColor: '#b45309',
  },
  {
    id: 'npc_02',
    name: 'Bác Bình',
    avatar: '👨‍🌾',
    age: 45,
    job: 'Thợ Rèn Lực Lưỡng',
    bio: 'Sở hữu lò rèn trung tâm, tính cách thẳng thắn và bộc trực.',
    defaultPersonality: 'aggressive',
    houseColor: '#b91c1c',
  },
  {
    id: 'npc_03',
    name: 'Cô Chi',
    avatar: '👩‍🏫',
    age: 32,
    job: 'Giáo Viên Làng',
    bio: 'Yêu sách vở, quan sát sắc sảo và luôn ghi chép nhật ký làng.',
    defaultPersonality: 'logical',
    houseColor: '#4338ca',
  },
  {
    id: 'npc_04',
    name: 'Chú Duy',
    avatar: '🧔',
    age: 41,
    job: 'Thợ Săn Rừng Sâu',
    bio: 'Quen thuộc từng ngóc ngách của khu rừng thông cấm.',
    defaultPersonality: 'observant',
    houseColor: '#15803d',
  },
  {
    id: 'npc_05',
    name: 'Chị Hà',
    avatar: '👩‍⚕️',
    age: 38,
    job: 'Dược Sĩ Thảo Mộc',
    bio: 'Nắm giữ những phương thuốc bí truyền từ các loại nấm rừng.',
    defaultPersonality: 'suspicious',
    houseColor: '#047857',
  },
  {
    id: 'npc_06',
    name: 'Khoa',
    avatar: '👨‍🎨',
    age: 26,
    job: 'Họa Sĩ Phong Cảnh',
    bio: 'Thích vẽ tranh đêm bên hồ sương mù, tính cách tự do phóng khoáng.',
    defaultPersonality: 'chaotic',
    houseColor: '#7c3aed',
  },
  {
    id: 'npc_07',
    name: 'Bà Lan',
    avatar: '👵',
    age: 62,
    job: 'Bà Chủ Tiệm Bánh',
    bio: 'Tiệm bánh luôn thơm lừng bánh mì nóng, tốt bụng với mọi người.',
    defaultPersonality: 'loyal',
    houseColor: '#c2410c',
  },
  {
    id: 'npc_08',
    name: 'Bác Minh',
    avatar: '👨‍✈️',
    age: 50,
    job: 'Người Giữ Ngọn Hải Đăng',
    bio: 'Canh gác ngọn hải đăng bên bờ đá, ít nói nhưng nhìn xa trông rộng.',
    defaultPersonality: 'observant',
    houseColor: '#0e7490',
  },
  {
    id: 'npc_09',
    name: 'Anh Nam',
    avatar: '🪵',
    age: 29,
    job: 'Người Đốn Củi',
    bio: 'Khỏe mạnh, sống một mình trong căn nhà gỗ rìa bìa rừng.',
    defaultPersonality: 'cautious',
    houseColor: '#854d0e',
  },
  {
    id: 'npc_10',
    name: 'Chị Phương',
    avatar: '🧵',
    age: 35,
    job: 'Thợ May Tinh Tế',
    bio: 'Nổi tiếng khéo tay, thường nghe ngóng được nhiều tin tức trong làng.',
    defaultPersonality: 'suspicious',
    houseColor: '#be185d',
  },
  {
    id: 'npc_11',
    name: 'Bác Quân',
    avatar: '🎣',
    age: 54,
    job: 'Ngư Dân Lão Luyện',
    bio: 'Đánh cá đêm trên hồ Lặng Sóng, quen với bóng tối và sự cô độc.',
    defaultPersonality: 'logical',
    houseColor: '#1d4ed8',
  },
  {
    id: 'npc_12',
    name: 'Vy',
    avatar: '📖',
    age: 22,
    job: 'Thủ Thư Thư Viện Cổ',
    bio: 'Cô gái trẻ say mê những cuốn sách cổ tích và truyền thuyết ngàn năm.',
    defaultPersonality: 'loyal',
    houseColor: '#4d7c0f',
  },

  // 2. Thêm Nhân vật đa dạng mới: Học giả & Nghệ nhân
  {
    id: 'npc_13',
    name: 'Thầy Hưng',
    avatar: '🔭',
    age: 56,
    job: 'Thiên Văn Học Gia',
    bio: 'Thường thức suốt đêm quan sát quỹ đạo các vì sao và tuần trăng bí ẩn.',
    defaultPersonality: 'logical',
    houseColor: '#312e81',
  },
  {
    id: 'npc_14',
    name: 'Cô Mai',
    avatar: '🎻',
    age: 27,
    job: 'Nghệ Sĩ Đàn Vĩ Cầm',
    bio: 'Tiếng đàn du dương giữa đêm khuya khiến dân làng vừa say đắm vừa tò mò.',
    defaultPersonality: 'chaotic',
    houseColor: '#9d174d',
  },
  {
    id: 'npc_15',
    name: 'Bác Tùng',
    avatar: '🕰️',
    age: 58,
    job: 'Thợ Chế Tác Đồng Hồ',
    bio: 'Chuyên sửa các cỗ máy thời gian và tháp chuông đồng hồ cổ kính của làng.',
    defaultPersonality: 'observant',
    houseColor: '#78350f',
  },
  {
    id: 'npc_16',
    name: 'Chị Ngọc',
    avatar: '🏺',
    age: 33,
    job: 'Thợ Gốm Mỹ Thuật',
    bio: 'Xoay bàn gốm bên ngọn lửa lò lung linh, linh cảm nghệ thuật sâu sắc.',
    defaultPersonality: 'cautious',
    houseColor: '#9a3412',
  },
  {
    id: 'npc_17',
    name: 'Ông Phúc',
    avatar: '⚖️',
    age: 65,
    job: 'Người Phân Xử Làng Cổ',
    bio: 'Giữ cán cân công lý của làng, không thiên vị bất kỳ một ai.',
    defaultPersonality: 'logical',
    houseColor: '#1e3a8a',
  },
  {
    id: 'npc_18',
    name: 'Linh Đan',
    avatar: '🔮',
    age: 24,
    job: 'Nhà Chiêm Tinh Trẻ',
    bio: 'Đọc điềm báo qua những lá bài cổ và làn khói hương trầm huyền bí.',
    defaultPersonality: 'suspicious',
    houseColor: '#581c87',
  },

  // 3. Thêm Nhân vật đa dạng mới: Người thám hiểm & Cư dân đêm
  {
    id: 'npc_19',
    name: 'Chú Cường',
    avatar: '⛏️',
    age: 44,
    job: 'Thợ Mỏ Địa Chất',
    bio: 'Lặn lội trong những hang động sâu thẳm dưới chân núi Mù Sương.',
    defaultPersonality: 'aggressive',
    houseColor: '#3f3f46',
  },
  {
    id: 'npc_20',
    name: 'Cô Thảo',
    avatar: '🌸',
    age: 30,
    job: 'Chủ Vườn Hoa Đêm',
    bio: 'Chăm sóc loài hoa quỳnh và dạ lý hương chỉ nở rộ vào nửa đêm.',
    defaultPersonality: 'loyal',
    houseColor: '#db2777',
  },
  {
    id: 'npc_21',
    name: 'Bảo',
    avatar: '🧭',
    age: 25,
    job: 'Nhà Thám Hiểm Rừng Mây',
    bio: 'Mang về làng những mẫu vật kỳ lạ từ vùng đất hoang sơ chưa ai đặt chân.',
    defaultPersonality: 'chaotic',
    houseColor: '#059669',
  },
  {
    id: 'npc_22',
    name: 'Bác Sáu',
    avatar: '🚣',
    age: 60,
    job: 'Người Lái Đò Bến Đục',
    bio: 'Đưa đò qua con sông sương mù chia cắt ngôi làng với thế giới bên ngoài.',
    defaultPersonality: 'observant',
    houseColor: '#0284c7',
  },
  {
    id: 'npc_23',
    name: 'Anh Vũ',
    avatar: '🐎',
    age: 31,
    job: 'Người Huấn Luyện Ngựa',
    bio: 'Chăm sóc bầy tuấn mã dũng mãnh, tai rất thính với tiếng bước chân đêm.',
    defaultPersonality: 'aggressive',
    houseColor: '#854d0e',
  },
  {
    id: 'npc_24',
    name: 'Chị Diệp',
    avatar: '🍵',
    age: 36,
    job: 'Bà Chủ Quán Trà Đạo',
    bio: 'Pha những ấm trà thảo mộc giúp dân làng an thần giữa những đêm bão giông.',
    defaultPersonality: 'cautious',
    houseColor: '#166534',
  },

  // 4. Thêm Nhân vật đa dạng mới: Người thợ & Cư dân kỳ cựu
  {
    id: 'npc_25',
    name: 'Bác Thành',
    avatar: '🍞',
    age: 52,
    job: 'Chủ Cối Xay Gió Làng',
    bio: 'Cánh cối xay gió của ông quay quanh năm trên đồi cao lộng gió.',
    defaultPersonality: 'loyal',
    houseColor: '#b45309',
  },
  {
    id: 'npc_26',
    name: 'Cô Quyên',
    avatar: '🕯️',
    age: 39,
    job: 'Thợ Đúc Nến Thơm',
    bio: 'Những ngọn nến sáp ong của cô soi sáng mọi ngôi nhà khi màn đêm buông xuống.',
    defaultPersonality: 'observant',
    houseColor: '#d97706',
  },
  {
    id: 'npc_27',
    name: 'Hải',
    avatar: '🏹',
    age: 23,
    job: 'Xạ Thủ Trẻ',
    bio: 'Bắn cung bách phát bách trúng, luôn canh gác ở cổng làng phía Bắc.',
    defaultPersonality: 'aggressive',
    houseColor: '#15803d',
  },
  {
    id: 'npc_28',
    name: 'Bà Mười',
    avatar: '🧶',
    age: 71,
    job: 'Nghệ Nhân Đan Len',
    bio: 'Bà cụ hiền từ ngồi đan áo ấm trước hiên nhà, chuyện gì trong làng bà cũng biết.',
    defaultPersonality: 'cautious',
    houseColor: '#be123c',
  },
  {
    id: 'npc_29',
    name: 'Chú Lâm',
    avatar: '🐝',
    age: 47,
    job: 'Người Nuôi Ong Rừng',
    bio: 'Thu hoạch mật ong rừng tinh khiết, rất nhạy cảm với mùi hương lạ trong gió.',
    defaultPersonality: 'observant',
    houseColor: '#ca8a04',
  },
  {
    id: 'npc_30',
    name: 'Chị Yến',
    avatar: '🌾',
    age: 34,
    job: 'Chủ Nông Trại Lúa Mì',
    bio: 'Quản lý cánh đồng vàng óng ả bao quanh ngôi làng, tính tình xốc vác.',
    defaultPersonality: 'loyal',
    houseColor: '#65a30d',
  },
  {
    id: 'npc_31',
    name: 'Tuấn',
    avatar: '🎸',
    age: 21,
    job: 'Nhạc Công Du Mục',
    bio: 'Chàng trai lang bạt mang theo cây đàn gỗ, kể những câu chuyện ly kỳ khắp phương xa.',
    defaultPersonality: 'chaotic',
    houseColor: '#9333ea',
  },
  {
    id: 'npc_32',
    name: 'Cụ Trí',
    avatar: '📜',
    age: 75,
    job: 'Nhà Sử Học Làng Cổ',
    bio: 'Lưu giữ những bản đồ cổ và ghi chép về các thế hệ khai phá ngôi làng từ thế kỷ trước.',
    defaultPersonality: 'logical',
    houseColor: '#374151',
  },
  {
    id: 'npc_33',
    name: 'Cô Hạnh',
    avatar: '🍲',
    age: 42,
    job: 'Đầu Bếp Quán Trọ Quả Sồi',
    bio: 'Mỗi tối quán trọ của cô luôn đông đúc người bàn tán về tin tức trong ngày.',
    defaultPersonality: 'suspicious',
    houseColor: '#c2410c',
  },
  {
    id: 'npc_34',
    name: 'Đức',
    avatar: '🛡️',
    age: 28,
    job: 'Đội Trưởng Dân Phòng',
    bio: 'Thường xuyên tuần tra ban đêm cùng chiếc khiên đồng và ngọn đuốc sáng.',
    defaultPersonality: 'aggressive',
    houseColor: '#1e40af',
  },
  {
    id: 'npc_35',
    name: 'Chị Bích',
    avatar: '🍎',
    age: 37,
    job: 'Chủ Vườn Táo Đỏ',
    bio: 'Sở hữu vườn táo xum xuê nơi chim muông thường tụ họp mỗi buổi bình minh.',
    defaultPersonality: 'loyal',
    houseColor: '#dc2626',
  },
  {
    id: 'npc_36',
    name: 'Ông Khánh',
    avatar: '🧪',
    age: 63,
    job: 'Nhà Giả Kim Cổ Truyền',
    bio: 'Nghiên cứu sự biến đổi của kim loại và các loại tinh dầu kỳ bí dưới tầng hầm đá.',
    defaultPersonality: 'logical',
    houseColor: '#0f766e',
  },
];

// Alias for backward compatibility
export const DEFAULT_VILLAGE_NPCS: NPCBaseTemplate[] = ALL_VILLAGE_NPCS.slice(0, 12);

/**
 * Generates a randomized, highly diverse cast of 12 distinct villagers from the 36+ template roster.
 * Shuffles personalities and background flavor so no two playthroughs feel identical!
 */
export function getRandomVillageCast(count: number = 12): NPCBaseTemplate[] {
  const shuffledPool = [...ALL_VILLAGE_NPCS].sort(() => Math.random() - 0.5);
  const selected = shuffledPool.slice(0, count);

  const personalities: WerewolfPersonality[] = ['cautious', 'aggressive', 'suspicious', 'logical', 'loyal', 'chaotic', 'observant'];

  return selected.map((tmpl, idx) => {
    // 30% chance to have a randomized dynamic personality variant for dynamic replayability
    const shouldVaryPersonality = Math.random() < 0.35;
    const finalPersonality = shouldVaryPersonality 
      ? personalities[Math.floor(Math.random() * personalities.length)]
      : tmpl.defaultPersonality;

    return {
      ...tmpl,
      id: `npc_${String(idx + 1).padStart(2, '0')}_${tmpl.id}`,
      defaultPersonality: finalPersonality,
    };
  });
}
