import { WerewolfPersonality, PersonalityProfile } from './werewolfTypes';

export const PERSONALITY_PROFILES: Record<WerewolfPersonality, PersonalityProfile> = {
  cautious: {
    id: 'cautious',
    name: 'Thận Trọng',
    badge: '🛡️',
    description: 'Ít mạo hiểm, luôn ưu tiên bảo toàn tính mạng và tin cậy những người có bằng chứng rõ ràng.',
    riskTolerance: 0.2,
    aggression: 0.2,
    skepticism: 0.6,
    memoryRetention: 0.9,
  },
  aggressive: {
    id: 'aggressive',
    name: 'Quyết Đoán',
    badge: '⚡',
    description: 'Hành động nhanh, dứt khoát, ưu tiên loại bỏ các mục tiêu nguy hiểm hoặc có sức ảnh hưởng.',
    riskTolerance: 0.8,
    aggression: 0.9,
    skepticism: 0.7,
    memoryRetention: 0.6,
  },
  suspicious: {
    id: 'suspicious',
    name: 'Đa Nghi',
    badge: '👁️',
    description: 'Dễ nghi ngờ hành vi bất thường của người khác, điểm hoài nghi thay đổi liên tục.',
    riskTolerance: 0.4,
    aggression: 0.6,
    skepticism: 0.95,
    memoryRetention: 0.8,
  },
  logical: {
    id: 'logical',
    name: 'Lý Trí',
    badge: '🧠',
    description: 'Phân tích dựa trên chuỗi sự kiện lịch sử, loại trừ mâu thuẫn để đưa ra quyết định chuẩn xác.',
    riskTolerance: 0.5,
    aggression: 0.4,
    skepticism: 0.75,
    memoryRetention: 0.95,
  },
  loyal: {
    id: 'loyal',
    name: 'Trung Thành',
    badge: '🤝',
    description: 'Bảo vệ đồng minh, tin tưởng vào những người từng giúp đỡ mình hoặc đã được kiểm chứng.',
    riskTolerance: 0.6,
    aggression: 0.3,
    skepticism: 0.3,
    memoryRetention: 0.85,
  },
  chaotic: {
    id: 'chaotic',
    name: 'Khó Đoán',
    badge: '🎲',
    description: 'Hành động bất ngờ, linh hoạt, đôi khi đưa ra quyết định khó lường nhưng có tính đột biến.',
    riskTolerance: 0.9,
    aggression: 0.7,
    skepticism: 0.5,
    memoryRetention: 0.5,
  },
  observant: {
    id: 'observant',
    name: 'Tinh Tế',
    badge: '🔍',
    description: 'Ghi nhớ chi tiết từng diễn biến ban đêm, phát hiện những chi tiết mà người khác bỏ qua.',
    riskTolerance: 0.3,
    aggression: 0.3,
    skepticism: 0.8,
    memoryRetention: 1.0,
  },
};

export interface NPCBaseTemplate {
  id: string;
  name: string;
  avatar: string;
  age: number;
  job: string;
  bio: string;
  defaultPersonality: WerewolfPersonality;
  houseColor: string;
}

export const DEFAULT_VILLAGE_NPCS: NPCBaseTemplate[] = [
  {
    id: 'npc_01',
    name: 'Cụ An',
    avatar: '👴',
    age: 68,
    job: 'Trưởng Thôn',
    bio: 'Người uyên bác nắm giữ chìa khóa tháp chuông làng cổ.',
    defaultPersonality: 'cautious',
    houseColor: '#b45309',
  },
  {
    id: 'npc_02',
    name: 'Bác Bình',
    avatar: '👨‍🌾',
    age: 45,
    job: 'Thợ Rèn Lực Lưỡng',
    bio: 'Sở hữu lò rèn trung tâm, tính cách thẳng thắn và bộc trực.',
    defaultPersonality: 'aggressive',
    houseColor: '#b91c1c',
  },
  {
    id: 'npc_03',
    name: 'Cô Chi',
    avatar: '👩‍🏫',
    age: 32,
    job: 'Giáo Viên Làng',
    bio: 'Yêu sách vở, quan sát sắc sảo và luôn ghi chép nhật ký làng.',
    defaultPersonality: 'logical',
    houseColor: '#4338ca',
  },
  {
    id: 'npc_04',
    name: 'Chú Duy',
    avatar: '🧔',
    age: 41,
    job: 'Thợ Săn Rừng Sâu',
    bio: 'Quen thuộc từng ngóc ngách của khu rừng thông cấm.',
    defaultPersonality: 'observant',
    houseColor: '#15803d',
  },
  {
    id: 'npc_05',
    name: 'Chị Hà',
    avatar: '👩‍⚕️',
    age: 38,
    job: 'Dược Sĩ Thảo Mộc',
    bio: 'Nắm giữ những phương thuốc bí truyền từ các loại nấm rừng.',
    defaultPersonality: 'suspicious',
    houseColor: '#047857',
  },
  {
    id: 'npc_06',
    name: 'Khoa',
    avatar: '👨‍🎨',
    age: 26,
    job: 'Họa Sĩ Phong Cảnh',
    bio: 'Thích vẽ tranh đêm bên hồ sương mù, tính cách tự do phóng khoáng.',
    defaultPersonality: 'chaotic',
    houseColor: '#7c3aed',
  },
  {
    id: 'npc_07',
    name: 'Bà Lan',
    avatar: '👵',
    age: 62,
    job: 'Bà Chủ Tiệm Bánh',
    bio: 'Tiệm bánh luôn thơm lừng bánh mì nóng, tốt bụng với mọi người.',
    defaultPersonality: 'loyal',
    houseColor: '#c2410c',
  },
  {
    id: 'npc_08',
    name: 'Bác Minh',
    avatar: '👨‍✈️',
    age: 50,
    job: 'Người Giữ Ngọn Hải Đăng',
    bio: 'Canh gác ngọn hải đăng bên bờ đá, ít nói nhưng nhìn xa trông rộng.',
    defaultPersonality: 'observant',
    houseColor: '#0e7490',
  },
  {
    id: 'npc_09',
    name: 'Anh Nam',
    avatar: '🪵',
    age: 29,
    job: 'Người Đốn Củi',
    bio: 'Khỏe mạnh, sống một mình trong căn nhà gỗ rìa bìa rừng.',
    defaultPersonality: 'cautious',
    houseColor: '#854d0e',
  },
  {
    id: 'npc_10',
    name: 'Chị Phương',
    avatar: '🧵',
    age: 35,
    job: 'Thợ May Tinh Tế',
    bio: 'Nổi tiếng khéo tay, thường nghe ngóng được nhiều tin tức trong làng.',
    defaultPersonality: 'suspicious',
    houseColor: '#be185d',
  },
  {
    id: 'npc_11',
    name: 'Bác Quân',
    avatar: '🎣',
    age: 54,
    job: 'Ngư Dân Lão Luyện',
    bio: 'Đánh cá đêm trên hồ Lặng Sóng, quen với bóng tối và sự cô độc.',
    defaultPersonality: 'logical',
    houseColor: '#1d4ed8',
  },
  {
    id: 'npc_12',
    name: 'Vy',
    avatar: '📖',
    age: 22,
    job: 'Thủ Thư Thư Viện Cổ',
    bio: 'Cô gái trẻ say mê những cuốn sách cổ tích và truyền thuyết ngàn năm.',
    defaultPersonality: 'loyal',
    houseColor: '#4d7c0f',
  },
];
